/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author natalia
 */
public class Editor extends javax.swing.JFrame {
public File fichero;
    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ElegirGui = new javax.swing.JButton();
        JPEGaBMP = new javax.swing.JButton();
        mostrarImagen = new javax.swing.JLabel();
        copiaJPEG = new javax.swing.JButton();
        RVAS = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        ByN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ElegirGui.setBackground(new java.awt.Color(153, 153, 153));
        ElegirGui.setForeground(new java.awt.Color(204, 255, 204));
        ElegirGui.setText("elegir");
        ElegirGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirGuiActionPerformed(evt);
            }
        });

        JPEGaBMP.setText("JPEG a BMP y visceversa");
        JPEGaBMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPEGaBMPActionPerformed(evt);
            }
        });

        copiaJPEG.setText("copia JPEG");
        copiaJPEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiaJPEGActionPerformed(evt);
            }
        });

        RVAS.setText("rojo - verde - azul -sepia");
        RVAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RVASActionPerformed(evt);
            }
        });

        modificar.setText("modificar");

        ByN.setText("Blanco y Negro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPEGaBMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(copiaJPEG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RVAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ByN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(mostrarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ElegirGui, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ElegirGui)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(JPEGaBMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(copiaJPEG)
                        .addGap(18, 18, 18)
                        .addComponent(RVAS)
                        .addGap(18, 18, 18)
                        .addComponent(modificar)
                        .addGap(18, 18, 18)
                        .addComponent(ByN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(mostrarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElegirGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirGuiActionPerformed
JFileChooser escojerImagen = new JFileChooser(); 
        int eleccion = escojerImagen.showOpenDialog(this); 
       
if(eleccion ==JFileChooser.APPROVE_OPTION){
        fichero=escojerImagen.getSelectedFile();
    ImageIcon imagen = new ImageIcon(fichero.getPath());
Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(mostrarImagen.getWidth(), mostrarImagen.getHeight(), Image.SCALE_DEFAULT));
mostrarImagen.setIcon(icono);
}

    }//GEN-LAST:event_ElegirGuiActionPerformed
String uno = "jpg";
    private void JPEGaBMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPEGaBMPActionPerformed
 if(fichero.getName().contains(uno)){
        
        ImageHandler imagen = new JPEGtoBMPImage(fichero.getName(), fichero.getPath());
try {
    JPEGHandler.runHandler(imagen);
         
}catch(Exception e){
    System.out.println("---error-----");
}} else {
 ImageHandler imagen = new BMPtoJPEGImage(fichero.getName(), fichero.getPath());
try {
    JPEGHandler.runHandler(imagen);
         
}catch(Exception e){
    System.out.println("---error-----");
}
 
 }
 
    }//GEN-LAST:event_JPEGaBMPActionPerformed

    private void copiaJPEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiaJPEGActionPerformed

ImageHandler imagen = new JPEGImageCopy(fichero.getName(), fichero.getPath());
try {
    JPEGHandler.runHandler(imagen);
         
}catch(Exception e){
    System.out.println("---error-----");
}
    }//GEN-LAST:event_copiaJPEGActionPerformed

    private void RVASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RVASActionPerformed
         ImageHandler imagen = new JPEGImageHandlerColors(fichero.getName(), fichero.getPath());

        try {
            JPEGHandler.runHandler(imagen);
        } catch (Exception e) {
            System.err.println("Error RGB: " + e.getMessage());
        }   
    }//GEN-LAST:event_RVASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ByN;
    private javax.swing.JButton ElegirGui;
    private javax.swing.JButton JPEGaBMP;
    private javax.swing.JButton RVAS;
    private javax.swing.JButton copiaJPEG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel mostrarImagen;
    // End of variables declaration//GEN-END:variables
}
